/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taqyeddine.billing.com;

import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author moi
 */
public class oo_billing extends javax.swing.JFrame {
    
    child_billing OnlyNumbers = new child_billing();

    /**
     * Creates new form oo_billing
     */
    public oo_billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1chrome = new javax.swing.JCheckBox();
        jtxtchrome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jCheckBoxcopper = new javax.swing.JCheckBox();
        jTextFieldcopper = new javax.swing.JTextField();
        jCheckBoxplastic = new javax.swing.JCheckBox();
        jTextFieldplastic = new javax.swing.JTextField();
        jCheckBoxtravel = new javax.swing.JCheckBox();
        jTextFieldtravel = new javax.swing.JTextField();
        jCheckBoxlabour = new javax.swing.JCheckBox();
        jTextFieldlabour = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBox27 = new javax.swing.JCheckBox();
        jTextField21 = new javax.swing.JTextField();
        jCheckBox28 = new javax.swing.JCheckBox();
        jTextField22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12), "billing system"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 153, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Billing System");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 1240, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\moi\\Pictures\\hqdefault (1).jpg")); // NOI18N
        jLabel9.setText("jLabel3");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 60, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\moi\\Pictures\\hqdefault (1).jpg")); // NOI18N
        jLabel10.setText("jLabel3");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1290, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 420, 520));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));

        jCheckBox1chrome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1chrome.setText("Chrome");
        jCheckBox1chrome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBox1chrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1chromeActionPerformed(evt);
            }
        });

        jtxtchrome.setColumns(20);
        jtxtchrome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtchrome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jtxtchrome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtchromeKeyTyped(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroup1.add(jCheckBox16);
        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox16.setText("5 %");
        jCheckBox16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        buttonGroup1.add(jCheckBox17);
        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox17.setSelected(true);
        jCheckBox17.setText("0 %");
        jCheckBox17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        buttonGroup1.add(jCheckBox18);
        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox18.setText("15 %");
        jCheckBox18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        buttonGroup1.add(jCheckBox19);
        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox19.setText("20 %");
        jCheckBox19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        buttonGroup1.add(jCheckBox20);
        jCheckBox20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox20.setText("25 %");
        jCheckBox20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        buttonGroup1.add(jCheckBox21);
        jCheckBox21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCheckBox21.setText("30 %");
        jCheckBox21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setName(""); // NOI18N

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Discount");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jCheckBoxcopper.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxcopper.setText("copper");
        jCheckBoxcopper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBoxcopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxcopperActionPerformed(evt);
            }
        });

        jTextFieldcopper.setColumns(20);
        jTextFieldcopper.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldcopper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextFieldcopper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcopperKeyTyped(evt);
            }
        });

        jCheckBoxplastic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxplastic.setText("plastic");
        jCheckBoxplastic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBoxplastic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxplasticActionPerformed(evt);
            }
        });

        jTextFieldplastic.setColumns(20);
        jTextFieldplastic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldplastic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextFieldplastic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldplasticKeyTyped(evt);
            }
        });

        jCheckBoxtravel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxtravel.setText("travel");
        jCheckBoxtravel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBoxtravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxtravelActionPerformed(evt);
            }
        });

        jTextFieldtravel.setColumns(20);
        jTextFieldtravel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldtravel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextFieldtravel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtravelKeyTyped(evt);
            }
        });

        jCheckBoxlabour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxlabour.setText("labour");
        jCheckBoxlabour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBoxlabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxlabourActionPerformed(evt);
            }
        });

        jTextFieldlabour.setColumns(20);
        jTextFieldlabour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldlabour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextFieldlabour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldlabourKeyTyped(evt);
            }
        });

        jTextField18.setColumns(20);
        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });

        jTextField19.setColumns(20);
        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField19KeyTyped(evt);
            }
        });

        jTextField20.setColumns(20);
        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });

        jCheckBox27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox27.setText("Taxable");
        jCheckBox27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });

        jTextField21.setColumns(20);
        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField21KeyTyped(evt);
            }
        });

        jCheckBox28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox28.setText("TVA");
        jCheckBox28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });

        jTextField22.setColumns(20);
        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jTextField22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField22KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Total Cost Of Labour");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total Cost Of Items");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total Cost Of Meliage");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tax");

        jTextField26.setColumns(20);
        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField26KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Subtotal");

        jTextField27.setColumns(20);
        jTextField27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField27KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total ");

        jTextField28.setColumns(20);
        jTextField28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField28KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox19)
                                    .addComponent(jCheckBox20)
                                    .addComponent(jCheckBox21)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxcopper)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldcopper, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxplastic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldplastic, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBox1chrome)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtchrome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxtravel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldtravel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxlabour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldlabour, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox28)
                            .addComponent(jCheckBox27)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)
                                .addGap(218, 218, 218)
                                .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtchrome)
                    .addComponent(jCheckBox1chrome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcopper, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxcopper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldplastic, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxplastic, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtravel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxtravel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlabour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxlabour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField21)
                                    .addComponent(jCheckBox27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox28)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(123, 123, 123))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 860, 520));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addGap(169, 169, 169)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(136, 136, 136)
                .addComponent(jButton3)
                .addGap(64, 64, 64))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 1290, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1chromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1chromeActionPerformed
        if (jCheckBox1chrome.isSelected()) {
            jtxtchrome.setEnabled(true);
            jtxtchrome.setText("");
            jtxtchrome.requestFocus();
        } else {
            jtxtchrome.setEnabled(false);
            jtxtchrome.setText("");
        }
    }//GEN-LAST:event_jCheckBox1chromeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        JTextField clearText= null;
        for (Component c :jPanel4.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText=(JTextField)c;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jCheckBoxlabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxlabourActionPerformed
        if (jCheckBoxlabour.isSelected()) {
            jTextFieldlabour.setEnabled(true);
            jTextFieldlabour.setText("");
            jTextFieldlabour.requestFocus();
        } else {
            jTextFieldlabour.setEnabled(false);
            jTextFieldlabour.setText("");
        }
    }//GEN-LAST:event_jCheckBoxlabourActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        child_billing iExet = new child_billing();
        
        try{
            iExet.iExitSystem();
        }catch(NumberFormatException e){
            JOptionPane.showConfirmDialog(null,"Billing System Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtchromeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtchromeKeyTyped
        
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jtxtchromeKeyTyped

    private void jTextFieldcopperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcopperKeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextFieldcopperKeyTyped

    private void jTextFieldplasticKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldplasticKeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextFieldplasticKeyTyped

    private void jTextFieldtravelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtravelKeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextFieldtravelKeyTyped

    private void jTextFieldlabourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldlabourKeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextFieldlabourKeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField19KeyTyped

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField20KeyTyped

    private void jTextField21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField21KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField21KeyTyped

    private void jTextField22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField22KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField22KeyTyped

    private void jTextField26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField26KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField26KeyTyped

    private void jTextField27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField27KeyTyped

    private void jTextField28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyTyped
        try {
            OnlyNumbers.iNemberOnly(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null,"billin system error");
        }
    }//GEN-LAST:event_jTextField28KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextArea1.setText("");
        JTextField clearText= null;
        for (Component c :jPanel4.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText=(JTextField)c;
                clearText.setText("0");
                clearText.setEnabled(false);
            }
        }
        
        JCheckBox clearcheckbox= null;
        for (Component q :jPanel4.getComponents()) {
            if (q.getClass().toString().contains("javax.swing.JCheckBox")) {
                clearcheckbox=(JCheckBox)q;
                clearcheckbox.setSelected(false);
            }
        }
        buttonGroup1.clearSelection();
        jCheckBox17.setSelected(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBoxcopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxcopperActionPerformed
        if (jCheckBoxcopper.isSelected()) {
            jTextFieldcopper.setEnabled(true);
            jTextFieldcopper.setText("");
            jTextFieldcopper.requestFocus();
        } else {
            jTextFieldcopper.setEnabled(false);
            jTextFieldcopper.setText("");
        }
    }//GEN-LAST:event_jCheckBoxcopperActionPerformed

    private void jCheckBoxplasticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxplasticActionPerformed
        if (jCheckBoxplastic.isSelected()) {
            jTextFieldplastic.setEnabled(true);
            jTextFieldplastic.setText("");
            jTextFieldplastic.requestFocus();
        } else {
            jTextFieldplastic.setEnabled(false);
            jTextFieldplastic.setText("");
        }
    }//GEN-LAST:event_jCheckBoxplasticActionPerformed

    private void jCheckBoxtravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxtravelActionPerformed
        if (jCheckBoxtravel.isSelected()) {
            jTextFieldtravel.setEnabled(true);
            jTextFieldtravel.setText("");
            jTextFieldtravel.requestFocus();
        } else {
            jTextFieldtravel.setEnabled(false);
            jTextFieldtravel.setText("");
        }
    }//GEN-LAST:event_jCheckBoxtravelActionPerformed

    private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox27ActionPerformed
        if (jCheckBox27.isSelected()) {
            jTextField21.setEnabled(true);
            jTextField21.setText("");
            jTextField21.requestFocus();
        } else {
            jTextField21.setEnabled(false);
            jTextField21.setText("");
        }
    }//GEN-LAST:event_jCheckBox27ActionPerformed

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        if (jCheckBox28.isSelected()) {
            jTextField22.setEnabled(true);
            jTextField22.setText("");
            jTextField22.requestFocus();
        } else {
            jTextField22.setEnabled(false);
            jTextField22.setText("");
        }
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double itax , isubtotal , itotal,ivat; 
        child_billing CostOfItems = new child_billing();
        CostOfItems.chrome=CostOfItems.pchrome*Double.parseDouble(jtxtchrome.getText());
        CostOfItems.copper=CostOfItems.pcopper*Double.parseDouble(jTextFieldcopper.getText());
        CostOfItems.plastic=CostOfItems.pplastic*Double.parseDouble(jTextFieldplastic.getText());
        CostOfItems.travel=CostOfItems.ptravel*Double.parseDouble(jTextFieldtravel.getText());
        CostOfItems.labour=CostOfItems.plabour*Double.parseDouble(jTextFieldlabour.getText());
    
    //=======================0%========================================
    
        if (jCheckBox17.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));
           
        }
        
        //==========================5%======================================
        if (jCheckBox16.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            isubtotal = isubtotal-((isubtotal*5)/100);
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));         
        }
        
        //==========================15%======================================
        if (jCheckBox18.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            isubtotal = isubtotal-((isubtotal*15)/100);
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));         
        }
        
        //==========================20%======================================
        if (jCheckBox19.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            isubtotal = isubtotal-((isubtotal*20)/100);
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));         
        }
        
        //==========================25%======================================
        if (jCheckBox20.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            isubtotal = isubtotal-((isubtotal*25)/100);
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));         
        }
        
        //==========================30%======================================
        if (jCheckBox21.isSelected()) {
            isubtotal = CostOfItems.GetAmount();
            isubtotal = isubtotal-((isubtotal*30)/100);
            itax = CostOfItems.cFindTax(isubtotal);
            ivat = CostOfItems.cFindVat(itax);
            itotal = itax+isubtotal+ivat;
            String subtotal = String.format("$%.2f",isubtotal);
            jTextField27.setText(subtotal);
            
            String VAT = String.format("$%.2f",ivat);
            jTextField22.setText(VAT);
            
            String tax = String.format("$%.2f",itax);
            jTextField26.setText(tax);
            String totale = String.format("$%.2f",itotal);
            jTextField28.setText(totale);
            
            jTextField21.setText(subtotal);
            jTextField20.setText(String.format("$%.2f",CostOfItems.travel));
            jTextField19.setText(String.format("$%.2f",CostOfItems.labour));
            jTextField18.setText(String.format("$%.2f",CostOfItems.plastic+CostOfItems.copper+CostOfItems.chrome));         
        }
        
        //=================================================================
        
        JTextField clearText= null;
        for (Component c :jPanel4.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText=(JTextField)c;
                clearText.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //================================================
        int refr = 1325 + (int)(Math.random()*4238);
        //=================================================
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
        tDate.format(timer.getTime());
        
        jTextArea1.append("\tBilling system:\n"+
                            "reference : \t\t\t"+refr+
                            "\n===============================================\n"+
                            "Chrome : \t\t\t"+jtxtchrome.getText()+"\n\n"+
                            "Copper : \t\t\t"+jTextFieldcopper.getText()+"\n\n"+
                            "plastic : \t\t\t"+jTextFieldplastic.getText()+"\n\n"+
                            "Travel:  \t\t\t"+jTextFieldtravel.getText()+"\n\n"+
                            "Labour : \t\t\t"+jTextFieldlabour.getText()+"\n\n"+
                            "VAT : \t\t\t"+jTextField22.getText()+"\n\n"+
                            "\n===============================================\n"+"\n"+
                            "Tax : \t\t\t"+jTextField26.getText()+"\n"+
                            "SubTotal : \t\t"+jTextField27.getText()+"\n"+
                            "Total : \t\t\t"+jTextField28.getText()+"\n"+
                            "==============================================="+
                            "\nDate: "+tDate.format(timer.getTime())+
                            "\tTime: "+tTime.format(timer.getTime())+
                            "\n\t\tThink you");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oo_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oo_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oo_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oo_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oo_billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox1chrome;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBoxcopper;
    private javax.swing.JCheckBox jCheckBoxlabour;
    private javax.swing.JCheckBox jCheckBoxplastic;
    private javax.swing.JCheckBox jCheckBoxtravel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextFieldcopper;
    private javax.swing.JTextField jTextFieldlabour;
    private javax.swing.JTextField jTextFieldplastic;
    private javax.swing.JTextField jTextFieldtravel;
    private javax.swing.JTextField jtxtchrome;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
